FROM    python:3.10.10-slim-bullseye
LABEL   APP=CEP_PYTHON_FLASK APP_MODULE=KEEP

ENV     APP_DIR=/app/
ENV     APP_MODULE=keep.py

ENV     VIACEP_CONTAINER_NAME=viacep.com.br
ENV     VIACEP_CONTAINER_PORT=80
ENV     VIACEP_CONTAINER_PROTOCOL=http
ENV     MAIN_CONTAINER_NAME=cep-main
ENV     MAIN_CONTAINER_PORT=5000
ENV     MAIN_CONTAINER_PROTOCOL=http
ENV     QUEST_CONTAINER_NAME=cep-quest
ENV     QUEST_CONTAINER_PORT=5001
ENV     QUEST_CONTAINER_PROTOCOL=http
ENV     KEEP_CONTAINER_NAME=cep-keep
ENV     KEEP_CONTAINER_PORT=5002
ENV     KEEP_CONTAINER_PROTOCOL=http
ENV     LIST_CSV_CONTAINER_NAME=cep-list_csv
ENV     LIST_CSV_CONTAINER_PORT=5003
ENV     LIST_CSV_CONTAINER_PROTOCOL=http
ENV     LIST_HTML_CONTAINER_NAME=cep-list_html
ENV     LIST_HTML_CONTAINER_PORT=5004
ENV     LIST_HTML_CONTAINER_PROTOCOL=http
ENV     SEARCH_CSV_CONTAINER_NAME=cep-search_csv
ENV     SEARCH_CSV_CONTAINER_PORT=5005
ENV     SEARCH_CSV_CONTAINER_PROTOCOL=http
ENV     SEARCH_HTML_CONTAINER_NAME=cep-search_html
ENV     SEARCH_HTML_CONTAINER_PORT=5006
ENV     SEARCH_HTML_CONTAINER_PROTOCOL=http

WORKDIR $APP_DIR
COPY    requirements-dev.txt $APP_DIR
COPY    requirements.txt $APP_DIR
RUN     python3 -m pip install -r requirements.txt
COPY    html/ $APP_DIR/html/
COPY    static-files/ $APP_DIR/static-files/
COPY    utils/ $APP_DIR/utils/
COPY    .pylintrc $APP_DIR
COPY    $APP_MODULE $APP_DIR
CMD     ["bash", "-c", "python3 $APP_MODULE"]
